name: selectzyme
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - cudf=24.12
  - cuml=24.12
  # - cuda-version=11.1  # insert your CUDA versions, you can get it from typing `nvidia-smi` in your terminal and upper right corner see the required version (might be 12.1)
  - pytorch
  - dash
  - pygraphviz  # maybe soon deprecated if GPU MST layout is available and integrated
  - ydata-profiling
  - opentsne
  - pip
  - pip:
    - -r requirements_pip_conda_docker.txt