name: my-env
channels:
  - nvidia
  - pytorch
  - conda-forge  # needs to be lowest hierarchy (last channel)
dependencies:
  - cudatoolkit=11.8  # insert your CUDA versions, you can get it from typing `nvidia-smi` in your terminal and upper right corner see the required version.
  - pytorch::pytorch
  - dash
  - pygraphviz
  - ydata-profiling
  - opentsne
  - pip
  - pip:
    - -r requirements_pip_conda_docker.txt
    