name: selectzyme
channels:
  - rapidsai  
  - pytorch
  - nvidia  
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit=11.8  # insert your CUDA versions, you can get it from typing `nvidia-smi` in your terminal and upper right corner see the required version.
  - cudf=24.12
  - cuml=24.12
  - pytorch::pytorch
  - dash
  - pygraphviz  # remove if feat: force directed MST layout gets removed; also if GPU accelerated layout is integrated
  - ydata-profiling
  - opentsne
  - ipykernel
  - pip
  - pip:
    - -r requirements_pip_conda_docker.txt
