name: my-env
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - cudf=23.12
  - cuml=23.12
  # - cuda-version=11.1  # 12.1
  - pytorch
  - dash
  - pygraphviz  # conda-forge  # conda install -y --channel conda-forge pygraphviz 
  - ydata-profiling  # conda install -c conda-forge ydata-profiling -y
  - opentsne  # "-"
  - pip
  - pip:
    - tqdm
    - plotly
    - requests
    - transformers
    - qdrant-client
    - hdbscan
    - h5py
    - taxoniq
    - biopython==1.84
    - dash-bootstrap-components==1.6.0
    - sentencepiece==0.2.0    
    - tiktoken==0.8.0
    - blobfile==3.0.0
    # - -r file:requirements.txt
    