name: my-env
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - cudf=23.12
  - cuml=23.12
  # - cuda-version=11.1  # 12.1
  - pytorch
  - dash
  - pygraphviz  # conda-forge  # nohup time conda install -y --channel conda-forge pygraphviz  
  - pip
  - pip:
    - tqdm
    - plotly
    - requests
    - fair-esm
    - qdrant-client
    - hdbscan
    - h5py
    - taxoniq
#    - dash-cytoscape==1.0.2
    - biopython==1.84
    # - -r file:requirements.txt
    