name: my-env
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - cudf=23.12
  - cuml=23.12
  - python=3.10
  - cuda-version=11.2
  - pytorch
  - cugraph=23.12
  - dash
  - pip
  - pip:
    - tqdm
    - fair-esm
    - qdrant-client
    - hdbscan
    # - -r file:requirements.txt
    