# Idea: faster builds by using uv package manager instead of pip
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# if OS out of memory comes again, continue with these steps: https://github.com/actions/runner-images/issues/709

name: Python application with uv

on:
  push:
    branches: [ "main", "12-CI-fix" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install and setup uv
      run: |
        python -m pip install uv
        uv venv  # Create a virtual environment at .venv.
        source .venv/bin/activate
        python --version

    - name: Install CUDA Toolkit
      run: |
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
        sudo sh -c 'echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-11-8

    - name: Configure LD_LIBRARY_PATH
      run: |
        ls /usr/local/cuda*
        echo "LD_LIBRARY_PATH=/usr/local/cuda-11-8/lib64:\$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "/usr/local/cuda-11-8/bin:\$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        uv pip install pytest pytest-cov 
        uv pip install --extra-index-url=https://pypi.nvidia.com cudf-cu11==24.10.* dask-cudf-cu11==24.10.* cuml-cu11==24.10.*
        if [ -f requirements.txt ]; then uv pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118; fi
        # todo: try next to install from pyproject.toml
        python --version

    - name: Run tests
      run: |
        which python
        source .venv/bin/activate  # fix: pytest not found (use uv venv!)
        python --version
        which python
        uv pip list
        python -m pytest -v tests/test_stack.py  # minimal initial test
        python -m pytest --cov=src/ -v tests/test_preprocessing.py
        python -m pytest --cov=src/ -v tests/test_visualizer.py
        python -m pytest --cov=src/ -v tests/test_preprocessing.py
        # python -m pytest --cov=src/ -v tests/test_*  # todo: test fails so far because no GPU runner used (test_embed.py and test_cuml_usage.py). 
