# Idea: faster builds by using uv package manager instead of pip
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# if OS out of memory comes again, continue with these steps: https://github.com/actions/runner-images/issues/709

name: Python application with uv

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # min hours day(month) month day(week)
    - cron: "0 0 1 */3 *"  # quarterly

permissions:
  contents: read

jobs:
  linting:
    name: Lint with Ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: python -m pip install ruff

      - name: Run Ruff Linting
        run: ruff check --output-format=github  # Ensures GitHub PR annotations    

  build_and_test:
    # needs: linting  # Dont run build and tests until linting succeeds
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install and setup uv
      run: |
        python -m pip install uv
        uv venv  # Create a virtual environment at .venv.
        source .venv/bin/activate
        python --version

    - name: Install dependencies
      run: |
        # sudo apt-get install graphviz graphviz-dev  # required for pygraphviz
        uv pip install pytest pytest-cov
        uv pip install --extra-index-url=https://pypi.nvidia.com cudf-cu11==24.10.* cuml-cu11==24.10.*
        uv pip install . --extra-index-url https://download.pytorch.org/whl/cu118
        python --version

    - name: Run tests
      run: |
        which python
        source .venv/bin/activate  # fix: pytest not found (use uv venv!)
        python --version
        which python
        uv pip list
        python -m pytest --cov=selectzyme/ -v tests/test_* -k 'not select and not TestLoadModelAndTokenizer and not TestGenEmbedding and not TestML and not cuml and not cuda and not TestQdrantDB'  # exclude tests requiring GPU/cuda
