# Idea: faster builds by using uv package manager instead of pip
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# if OS out of memory comes again, continue with these steps: https://github.com/actions/runner-images/issues/709

name: Python application with uv

on:
  push:
    branches: [ "main", "12-CI-fix" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install and setup uv
      run: |
        python -m pip install uv
        uv venv  # Create a virtual environment at .venv.
        source .venv/bin/activate
        python --version

    - name: Install dependencies
      run: |
        uv pip install pytest pytest-cov 
        uv pip install --extra-index-url=https://pypi.nvidia.com cudf-cu11==24.10.* dask-cudf-cu11==24.10.* cuml-cu11==24.10.*
        if [ -f requirements.txt ]; then uv pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118; fi
        # todo: try next to install from pyproject.toml
        python --version

    - name: Run tests
      run: |
        python --version
        uv pip list
        uv pip install pytest pytest-cov
        python -m pytest --cov=src/ -v tests/test_stack.py
        python -m pytest --cov=src/ -v tests/test_*
        pytest --cov=src/ -v tests/test_stack.py  # python -m causes no pytest found but its listed with uv pip list
        pytest --cov=src/ -v tests/test_*
